spring: 
  banner: 
    location: mybanner.txt  #默认banner.txt
  thymeleaf:
    mode: HTML # Template mode to be applied to templates. See also Thymeleaf's TemplateMode enum.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.
    cache: false
  devtools:
    restart:
      exclude: static/**
  #连接池配置
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: lovesz
    password: lovesz
    druid:
      # 配置测试查询语句
      validationQuery: SELECT 1 FROM DUAL
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 200
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # yml 或者 properties 配置了，就不需要配置configuration的servlet和filter了 .http://localhost:8889/druid/index.html
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true #是否启用StatFilter默认值false
        url-pattern: /*
        exclusions: /druid/*
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
        allow: 127.0.0.1
        deny: 192.168.1.73
  redis:
    host: 192.168.30.128
    port: 6379
#mybatis
mybatis:
  # 实体类扫描
  type-aliases-package: com.example.dto
  # 配置映射文件位置
  mapper-locations: classpath:mappers/*.xml
  # 开启驼峰匹配
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
  #http://localhost:8889/static/index.html 访问的是mystatic/index.html
  #这个设置的作用：访问静态资源文件要加static才行，不加会报错404
  #mvc: 
    #static-path-pattern: /static/**  
  #上面的是访问地址是以什么形式访问（是否加/static），但是访问的资源地址是下面的
  #优先级顺序为：META/resources > resources > static > public > templates
  #resources: 
    #static-locations: classpath:mystatic/
server: 
  port: 8889
  servlet: 
    context-path: /
#  error:
#    include-exception: true
#    path: /error

logging: 
  config: classpath:logback-dev-spring.xml
